/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DaftarRouteImport } from './routes/daftar'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PenugasanRouteImport } from './routes/penugasan'
import { Route as PenugasanIndexRouteImport } from './routes/penugasan.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarRoute = DaftarRouteImport.update({
  id: '/daftar',
  path: '/daftar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PenugasanRoute = PenugasanRouteImport.update({
  id: '/penugasan',
  path: '/penugasan',
  getParentRoute: () => rootRouteImport,
} as any)
const PenugasanIndexRoute = PenugasanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PenugasanRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/daftar': typeof DaftarRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/penugasan': typeof PenugasanRouteWithChildren
  '/penugasan/': typeof PenugasanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daftar': typeof DaftarRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/penugasan': typeof PenugasanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/daftar': typeof DaftarRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/penugasan': typeof PenugasanRouteWithChildren
  '/penugasan/': typeof PenugasanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/daftar' | '/dashboard' | '/login' | '/penugasan' | '/penugasan/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/daftar' | '/dashboard' | '/login' | '/penugasan'
  id:
    | '__root__'
    | '/'
    | '/daftar'
    | '/dashboard'
    | '/login'
    | '/penugasan'
    | '/penugasan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DaftarRoute: typeof DaftarRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PenugasanRoute: typeof PenugasanRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar': {
      id: '/daftar'
      path: '/daftar'
      fullPath: '/daftar'
      preLoaderRoute: typeof DaftarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/penugasan': {
      id: '/penugasan'
      path: '/penugasan'
      fullPath: '/penugasan'
      preLoaderRoute: typeof PenugasanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/penugasan/': {
      id: '/penugasan/'
      path: '/'
      fullPath: '/penugasan/'
      preLoaderRoute: typeof PenugasanIndexRouteImport
      parentRoute: typeof PenugasanRoute
    }
  }
}

interface PenugasanRouteChildren {
  PenugasanIndexRoute: typeof PenugasanIndexRoute
}

const PenugasanRouteChildren: PenugasanRouteChildren = {
  PenugasanIndexRoute: PenugasanIndexRoute,
}

const PenugasanRouteWithChildren = PenugasanRoute._addFileChildren(
  PenugasanRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DaftarRoute: DaftarRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PenugasanRoute: PenugasanRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
